version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - my-network

  deliveryservice:
    build:
      context: ./src/DeliveryService
    container_name: deliveryservice
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
    networks:
      - my-network

  paymentservice:
    build:
      context: ./src/PaymentService
    container_name: paymentservice
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
    networks:
      - my-network

  logservice:
    build:
      context: ./src/LogService
    container_name: logservice
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
    networks:
      - my-network

  customerservice:
    build:
      context: ./src/CustomerService
    container_name: customerservice
    environment:
      - ASPNETCORE_URLS=http://+:5004
    ports:
      - "5004:5004"
    depends_on:
      - rabbitmq
    networks:
      - my-network

  signatureexampleapi:
    build:
      context: .
      dockerfile: ./gateway/SignatureExampleAPI/Dockerfile
    container_name: signatureexampleapi
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - my-network

networks:
  my-network:
    driver: bridge