services:
  signatureexampleapi:
    image: ${DOCKER_REGISTRY-}signatureexampleapi
    build:
      context: .
      dockerfile: gateway/SignatureExampleAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
