version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  nginx:
    image: nginx
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - deliveryservice
      - paymentservice
      - logservice

  deliveryservice:
    build:
      context: ./src/DeliveryService
    container_name: deliveryservice
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  paymentservice:
    build:
      context: ./src/PaymentService
    container_name: paymentservice
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq

  logservice:
    build:
      context: ./src/LogService
    container_name: logservice
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq